### ISSUE TITLE
AsyncClient.login dont work

### ISSUE THREAD

**Issue by xllwhoami** [Slimakoi/Amino.py#88]
Hi, wanted to try amino.py
I saw in the documentation that there's an async, and I wanted to start with it, I wrote this code:
```python
import asyncio
from amino.async_client import AsyncClient
from amino.lib.util.exceptions import FailedLogin
from amino.async_socket import AsyncCallbacks, AsyncSocketHandler
from .config import config


client = AsyncClient()
socket_handler = AsyncSocketHandler(client)
callbacks = AsyncCallbacks(client)


@callbacks.event('on_text_message')
async def onmessage(data):
    print(data)


async def main():
    try:
        await client.login(email=config.email, password=config.password)
    except FailedLogin:
        return print('Login failed')
        
        
    await socket_handler.run_amino_socket()
        
        

if '__main__' == __name__:
    asyncio.run(main())
```

And it gives me:

```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/data/com.termux/files/home/inohit/inohit/__main__.py", line 30, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/inohit/inohit/__main__.py", line 20, in main
    await client.login(email=config.email, password=config.password)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/amino/async_client.py", line 211, in login
    async with self.session.post(f"{self.api}/g/s/auth/login", headers=self.parse_headers(data=data), data=data) as response:
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiohttp/helpers.py", line 700, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```

Please help me :)

(Don't look at the fact that I ran the program in termux)
By the way, update the discord link

**Comment by ok-isaid** [comment]
Did you find a solution?

**Comment by xllwhoami** [comment]
> Did you find a solution?



I found aminofix library (synchronous fix of this library), but amino developers added signatures to their api, and now it became impossible to use many methods without them
